.asdf

diff --git a/.github/workflows/create-image-and-deploy.yml b/.github/workflows/create-image-and-deploy.yml
--- a/.github/workflows/create-image-and-deploy.yml
+++ b/.github/workflows/create-image-and-deploy.yml
@@ -26,8 +26,18 @@ jobs:
             git init
             docker images
             git pull ${{secrets.REPO_URL}}
+            
+            (
             docker rmi -f ${{ secrets.D_IMAGE_NAME }}:latest
+            ) || (
+            echo "Not found docker image"
+            )
+            
+            (
             docker rmi -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest
+            ) || ( 
+            echo "Not found docker compose"
+            )
 
             docker compose down $(docker ps -a -q)
             docker-compose up -d
